---
- name: Install Requisite packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add User to Sudo Group
  user:
    name: "{{ansible_user}}"
    shell: /bin/bash
    groups:
      - sudo    
    append: yes
    state: present