---
- name: Install Package and its Dependencies
  apt: 
   name: 'ruby2.3'
   state: present

- name: Install Gem Required Packages
  gem: 
   name: "{{item}}"
   state: present
  with_items:
    - deb-s3
    - serverspec